kind: pipeline
name: default

steps:
  - name: run-test-cases
    image: maven:3.8.5-openjdk-17
    when:
      status:
        - failure
        - success
    commands:
      - git clone https://${GIT_ACCESS_TOKEN}@github.com/${GIT_REPO}.git
      - cp ApplicationIntegrationTest.java ${PROJECT_FOLDER_NAME}/src/test/java/com/newtonschool/question/ApplicationIntegrationTest.java
      - cd ${PROJECT_FOLDER_NAME}
      - mvn clean test
  - name: result
    image: maven:3.8.5-openjdk-17
    when:
      status:
        - failure
        - success
    commands:
      - cd ${PROJECT_FOLDER_NAME}/target/surefire-reports
      - cat TEST-com.newtonschool.question.ApplicationIntegrationTest.xml